# Generated by Django 5.0.14 on 2026-07-26 23:51

import apps.books.models
import apps.books.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=320, unique=True)),
                ('author', models.CharField(db_index=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('language', models.CharField(default='ar', max_length=10)),
                ('publication_year', models.PositiveIntegerField(blank=True, null=True)),
                ('pdf_file', models.FileField(upload_to=apps.books.models.book_pdf_upload_path, validators=[apps.books.validators.validate_pdf_file])),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=apps.books.models.book_cover_upload_path)),
                ('file_size_bytes', models.BigIntegerField(default=0, editable=False)),
                ('download_count', models.PositiveIntegerField(default=0, editable=False)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_books', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='books.subject')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['title'], name='books_book_title_d3218d_idx'), models.Index(fields=['author'], name='books_book_author_b941fe_idx')],
            },
        ),
    ]
